version: 2.1

commands:
  submodule-update:
    steps:
      - run: git submodule update --recursive --init deps/spiffing deps/rapidxml deps/sigslot
  apt-install:
    steps:
      - run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt-get install --quiet --yes --no-install-recommends \
              clang \
              cmake \
              googletest \
              libc++-dev \
              libc++abi-dev \
              libevent-dev \
              libicu-dev \
              libspdlog-dev \
              libssl-dev \
              libunbound-dev \
              ninja-build \
              pkg-config
  cmake-build:
    steps:
      - run: |
          mkdir ../build
          cd ../build
          cmake \
            -DCMAKE_C_COMPILER=/usr/bin/clang \
            -DCMAKE_CXX_COMPILER=/usr/bin/clang++ \
            -DCMAKE_INSTALL_PREFIX=/app/install \
            -DCMAKE_BUILD_TYPE=Release \
            -DVENDORED_DEPS=OFF \
            -GNinja \
            ../project
          export CMAKE_BUILD_PARALLEL_LEVEL=3
          cmake --build .
          cmake --build . --target test
          cmake --build . --target install

  submodule-update-vendored:
    steps:
      - run: git submodule update --recursive --init
  apt-install-vendored:
    steps:
      - run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt-get install --quiet --yes --no-install-recommends \
              build-essential \
              clang \
              cmake \
              libc++-dev \
              libc++abi-dev \
              libicu-dev \
              ninja-build
  build-openssl-vendored:
    steps:
      - run: |
          cd deps/openssl
          ./config --prefix=/usr/local --openssldir=/etc/ssl no-shared
          make -j3
  cmake-build-vendored:
    steps:
      - run: |
          mkdir ../build
          cd ../build
          cmake \
            -DCMAKE_C_COMPILER=/usr/bin/clang \
            -DCMAKE_CXX_COMPILER=/usr/bin/clang++ \
            -DCMAKE_INSTALL_PREFIX=/app/install \
            -DCMAKE_BUILD_TYPE=Release \
            -DVENDORED_DEPS=ON \
            -GNinja \
            ../project
          export CMAKE_BUILD_PARALLEL_LEVEL=3
          cmake --build .
          cmake --build . --target install

  linux-shared:
    parameters:
      after-deps:
        type: steps
        default: []
    steps:
      - checkout
      - submodule-update
      - apt-install
      - steps: << parameters.after-deps >>
      - cmake-build

  linux-shared-vendored:
    steps:
      - checkout
      - submodule-update-vendored
      - apt-install-vendored
      - build-openssl-vendored
      - cmake-build-vendored

jobs:

  build-docker:
    environment:
      IMAGE_NAME: surevinecom/metre
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - submodule-update
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest .

  build-ubuntu-lts:
    docker:
      - image: buildpack-deps:20.04-scm
    steps:
      - linux-shared

  build-ubuntu-lts-vendored:
    docker:
      - image: buildpack-deps:20.04-scm
    steps:
      - linux-shared-vendored

workflows:
  version: 2
  build-matrix:
    jobs:
      - build-docker
      - build-ubuntu-lts
      - build-ubuntu-lts-vendored
